#!/usr/bin/env python3
"""
CryptVault - Advanced AI-Powered Cryptocurrency Analysis Platform

A sophisticated cryptocurrency analysis tool that combines:
- Advanced pattern recognition
- Machine learning predictions (LSTM, Ensemble models)
- Real-time data fetching
- Technical analysis
- Risk assessment

Made by the MeridianAlgo Algorithmic Research Team (Quantum Meridian)

Usage:
    python cryptvault_cli.py [TICKER] [DAYS] [INTERVAL]

Examples:
    python cryptvault_cli.py BTC 60 1d                    # Bitcoin with chart
    python cryptvault_cli.py ETH 60 1d --save-chart eth.png  # Save chart
    python cryptvault_cli.py ADA 60 1d --no-chart        # Text only
    
    python cryptvault_cli.py --demo        # Quick demo
    python cryptvault_cli.py --help        # Show help
    
Note: Charts with pattern overlays are generated by default!
      Use --no-chart to disable or --save-chart to save to file.
"""

import sys
import argparse
import logging
import os
import platform

# Fix Windows console encoding for Unicode characters
if platform.system() == 'Windows':
    try:
        # Try to set UTF-8 encoding for Windows console
        if sys.stdout.encoding != 'utf-8':
            sys.stdout.reconfigure(encoding='utf-8')
    except (AttributeError, ValueError):
        # If reconfigure doesn't work, use errors='replace' to avoid crashes
        import io
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

# Import CLI commands
from cryptvault.cli.commands import (
    analyze_ticker,
    analyze_portfolio,
    compare_assets,
    show_demo,
    show_api_status,
    show_prediction_accuracy,
    start_live_analysis,
    open_desktop_charts
)
from cryptvault.cli.formatters import format_info, format_error
from cryptvault.__version__ import __version__


def setup_logging(verbose: bool = False):
    """
    Setup logging configuration.
    
    Args:
        verbose: Enable verbose logging
    """
    os.makedirs('logs', exist_ok=True)
    level = logging.INFO if verbose else logging.ERROR
    logging.basicConfig(
        level=level,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        handlers=[
            logging.StreamHandler(),
            logging.FileHandler('logs/cryptvault.log')
        ]
    )


def interactive_mode():
    """
    Interactive CryptVault mode.
    
    Provides an interactive shell for running multiple commands
    without restarting the CLI.
    """
    print("\n" + "=" * 70)
    print("CryptVault Interactive Mode")
    print("=" * 70)
    print("Commands: analyze, portfolio, compare, live, desktop, status, help, exit")
    print("=" * 70 + "\n")
    
    while True:
        try:
            command = input("\ncryptvault> ").strip()
            
            if not command:
                continue
            
            parts = command.split()
            cmd = parts[0].lower()
            
            if cmd in ['exit', 'quit', 'q']:
                print(format_info("Goodbye!"))
                break
            
            elif cmd == 'help':
                print("\nAvailable commands:")
                print("  analyze <SYMBOL> [DAYS] [INTERVAL] - Analyze cryptocurrency")
                print("  portfolio <SYMBOL:AMOUNT> ...      - Analyze portfolio")
                print("  compare <SYMBOL> ...               - Compare assets")
                print("  live <SYMBOL>                      - Start live analysis")
                print("  desktop                            - Open desktop charts")
                print("  status                             - Show API status")
                print("  accuracy [DAYS]                    - Show ML accuracy report")
                print("  demo                               - Show demo")
                print("  help                               - Show this help")
                print("  exit                               - Exit interactive mode")
            
            elif cmd == 'status':
                show_api_status()
            
            elif cmd == 'demo':
                show_demo()
            
            elif cmd == 'desktop':
                open_desktop_charts()
            
            elif cmd == 'analyze':
                if len(parts) >= 2:
                    ticker = parts[1]
                    days = int(parts[2]) if len(parts) > 2 else 30
                    interval = parts[3] if len(parts) > 3 else '1d'
                    analyze_ticker(ticker, days, interval)
                else:
                    print(format_error("Usage: analyze <SYMBOL> [DAYS] [INTERVAL]"))
            
            elif cmd == 'portfolio':
                if len(parts) >= 2:
                    holdings = parts[1:]
                    analyze_portfolio(holdings)
                else:
                    print(format_error("Usage: portfolio <SYMBOL:AMOUNT> ..."))
            
            elif cmd == 'compare':
                if len(parts) >= 2:
                    symbols = parts[1:]
                    compare_assets(symbols)
                else:
                    print(format_error("Usage: compare <SYMBOL> ..."))
            
            elif cmd == 'live':
                if len(parts) >= 2:
                    start_live_analysis(parts[1])
                else:
                    print(format_error("Usage: live <SYMBOL>"))
            
            elif cmd == 'accuracy':
                days = int(parts[1]) if len(parts) > 1 else 30
                show_prediction_accuracy(days)
            
            else:
                print(format_error(f"Unknown command: '{cmd}'. Type 'help' for available commands."))
                
        except KeyboardInterrupt:
            print("\n" + format_info("Use 'exit' to quit"))
        except ValueError as e:
            print(format_error(f"Invalid input: {e}"))
        except Exception as e:
            print(format_error(f"Error: {e}"))


def main():
    """Main CryptVault CLI function."""
    parser = argparse.ArgumentParser(
        description="CryptVault - Advanced AI-Powered Cryptocurrency Analysis",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s BTC 60 1d                         # Bitcoin with interactive chart
  %(prog)s ETH 60 1d --save-chart eth.png    # Save chart to file
  %(prog)s ADA 60 1d --no-chart              # Text-only analysis
  %(prog)s --desktop                         # Open desktop charts window
  %(prog)s --demo                            # Quick demo
  %(prog)s --interactive                     # Interactive mode
  
Charts with pattern overlays are generated by default!

Aliases:
  -d, --desktop     Open desktop charts
  -i, --interactive Interactive mode
  -v, --verbose     Verbose output
        """
    )
    
    # Positional arguments
    parser.add_argument(
        'ticker',
        nargs='?',
        default='BTC',
        help='Cryptocurrency ticker symbol (default: BTC)'
    )
    parser.add_argument(
        'days',
        nargs='?',
        type=int,
        default=30,
        help='Number of days of data (default: 30)'
    )
    parser.add_argument(
        'interval',
        nargs='?',
        default='1d',
        help='Data interval: 1h, 4h, 1d (default: 1d)'
    )
    
    # Command options
    parser.add_argument(
        '--demo',
        action='store_true',
        help='Run quick demo'
    )
    parser.add_argument(
        '--status',
        action='store_true',
        help='Show API status'
    )
    parser.add_argument(
        '--portfolio',
        nargs='+',
        metavar='SYMBOL:AMOUNT',
        help='Analyze portfolio: BTC:0.5 ETH:10 ADA:1000'
    )
    parser.add_argument(
        '--compare',
        nargs='+',
        metavar='SYMBOL',
        help='Compare multiple assets: BTC ETH ADA'
    )
    parser.add_argument(
        '--live',
        metavar='SYMBOL',
        help='Start live analysis for symbol'
    )
    parser.add_argument(
        '--desktop', '-d',
        action='store_true',
        help='Open desktop charts in new window'
    )
    parser.add_argument(
        '--accuracy',
        action='store_true',
        help='Show ML prediction accuracy report'
    )
    parser.add_argument(
        '--interactive', '-i',
        action='store_true',
        help='Interactive mode'
    )
    
    # Output options
    parser.add_argument(
        '--verbose', '-v',
        action='store_true',
        help='Verbose output with detailed information'
    )
    parser.add_argument(
        '--no-chart',
        action='store_true',
        help='Disable automatic chart generation'
    )
    parser.add_argument(
        '--save-chart',
        metavar='PATH',
        help='Save chart to file instead of displaying interactively'
    )
    
    # Version
    parser.add_argument(
        '--version',
        action='version',
        version=f'CryptVault {__version__}'
    )
    
    args = parser.parse_args()
    
    # Setup logging
    setup_logging(args.verbose)
    
    try:
        # Handle different command modes
        if args.demo:
            show_demo()
        
        elif args.status:
            show_api_status()
        
        elif args.portfolio:
            success = analyze_portfolio(args.portfolio, verbose=args.verbose)
            if not success:
                sys.exit(1)
        
        elif args.compare:
            success = compare_assets(args.compare, verbose=args.verbose)
            if not success:
                sys.exit(1)
        
        elif args.live:
            start_live_analysis(args.live, verbose=args.verbose)
        
        elif args.desktop:
            open_desktop_charts(verbose=args.verbose)
        
        elif args.accuracy:
            show_prediction_accuracy(verbose=args.verbose)
        
        elif args.interactive:
            interactive_mode()
        
        else:
            # Default: analyze ticker
            success = analyze_ticker(
                args.ticker,
                args.days,
                args.interval,
                verbose=args.verbose,
                generate_chart=True,
                save_chart_path=args.save_chart,
                no_chart=args.no_chart
            )
            if not success:
                sys.exit(1)
                
    except KeyboardInterrupt:
        print("\n" + format_info("Interrupted"))
        sys.exit(0)
    except Exception as e:
        print(format_error(f"Unexpected error: {e}"))
        if args.verbose:
            import traceback
            traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
